# Generated by Django 6.0.2 on 2026-02-06 05:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0003_rename_model_blog'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blog',
            old_name='if_featured',
            new_name='is_featured',
        ),
    ]
